spring:
  mvc:
    servlet:
      load-on-startup: 1
  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: ${RABBIT_PORT:5672}
  redis:
    host: ${REDIS_HOST:localhost} # Redis服务器地址
    port: ${REDIS_PORT:6379}      # Redis服务器连接端口
    database: ${REDIS_DATABASE:1} # Redis数据库索引（默认为0）
#    password:                     # Redis服务器连接密码（默认为空）
#    pool:
#      max-active: 8               # 连接池最大连接数（使用负值表示没有限制）
#      max-wait: -1                # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-idle: 8                 # 连接池中的最大空闲连接
#      min-idle: 0                 # 连接池中的最小空闲连接
#    timeout: 0                    # 连接超时时间（毫秒）
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/local}
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 600000
logging:
  level:
    java.sql: debug
    com.hand.spring: debug