server:
  port: ${PORT:8089}
#mybatis:
#  mapper-locations: classpath*:com/hand/**/*Mapper.xml
spring:
  cloud:
    stream:
      bindings:
        springCloudBusInput:
          group: spring-test-service
  datasource:
      url: jdbc:mysql://10.213.0.40:3306/dev-gamepacket?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=5
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PWD:root}
      driver-class-name: com.mysql.jdbc.Driver
pagehelper:
  row-bounds-with-count: true
  auto-dialect: true
  reasonable: false